config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  ##################################ADMINS ROUTES##################################
  get '/admin' => 'admins#dashboard', :as => 'admin_dashboard'
  get '/admin/transactions' => 'admins#transactions', :as => 'admin_transactions'
  post '/admin/users' => 'admins#create_user', :as => 'admin_create_user'
  get '/admin/users/new_user' => 'admins#new_user', :as => 'admin_new_user'
  get 'admin/users/:id/edit' => 'admins#edit_user', as: 'admin_edit_user'
  get 'admin/users/:id/activate' => 'admins#activate_user', as: 'admin_activate_user'
  get 'admin/users/:id/' => 'admins#show_user', as: 'admin_show_user'
  patch 'admin/users/:id' => 'admins#update_user', as: 'admin_update_user'
  #################################END ADMIN ROUTES#################################

  ##################################TRADERS ROUTES##################################
  get '/trader' => 'traders#dashboard', :as => 'trader_dashboard'
  get '/portfolio' => 'traders#portfolio', :as => 'trader_portfolio'
  get '/transactions' => 'traders#transactions', :as => 'trader_transactions'
  ################################END TRADERS ROUTES################################

  ################################TRANSACTIONS ROUTES###############################
  # get '/transactions' => 'transactions#index', :as => 'transactions'
  get '/stocks/:stock_id/transactions' => 'transactions#stock_transactions', :as => 'stock_transactions'
  post '/stocks/:stock_id/transactions' => 'transactions#create_stock_transaction', :as => 'create_stock_transactions'
  get '/stocks/:stock_id/transactions/buy' => 'transactions#buy', :as => 'buy_stock'
  get '/stocks/:stock_id/transactions/:id/sell' => 'transactions#sell', :as => 'sell_stock'
  patch '/stocks/:stock_id/transactions/:id' => 'transactions#update_transaction', :as => 'update_stock_transaction'
  ##############################END TRANSACTIONS ROUTES##############################

end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
  before_action :authenticate_user!, :check_authorization, :get_all_tables, :get_user_and_users, :get_current_user_transactions, :set_api
  
  def dashboard
    if params[:q].present?
      begin
        @quote = @client.quote(params[:q])
      rescue => exception

      end
    end
  end

  def portfolio
    @active = @transactions.where(is_active: true)
    @unique = @active.select('stock_id as stock_id, sum(quantity) as total_quantity').group(:stock_id)
  end

  def transactions
    @transactions = @user.transactions.order(:created_at).reverse_order
  end

  def get_current_user_transactions
    @transactions = @user.transactions
  end

  def get_user_and_users
    @user = current_user
    @users = User.all
  end

  def get_all_tables
    @users = User.all 
    @stocks = Stock.all 
    @transactions = Transaction.all
  end

  def set_api
    require 'iex-ruby-client'
    @client = IEX::Api::Client.new
    @client_list = @client.stock_market_list(:mostactive)
  end

  def check_authorization
    if current_user.role == 'admin'
      redirect_to admin_dashboard_path, notice: 'Access Denied'
    end
  end

end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/traders/dashboard.html.erb
<div class="mb-4">
    <h1 class="w-full text-xl font-bold text-white mb-2">Welcome, <%= current_user.first_name.upcase %></h1>
    <% if !current_user.is_active %>
      <div>
        <p>Your account is not activated yet. Buying of shares is prohibited.</p>
      </div>
    <% end %>
</div>

<div class="mb-5">
  <%= form_with(url: trader_dashboard_path, method: :get) do |form| %>
    <%= form.label :q, "Search Company", class: 'mb-2 text-sm font-medium sr-only text-gray-300' %>
    <div class="relative">
      <%= form.text_field :q, placeholder: 'Search Company (SYM)', class: 'block p-4 w-full text-sm rounded-lg border focus:border-blue-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 dark:focus:border-blue-500' %>
      <%= form.submit "Search", class: 'text-white absolute right-2.5 bottom-2.5 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-4 py-2 bg-blue-600 hover:bg-blue-700 focus:ring-blue-800 hover:cursor-pointer' %>
    </div>
  <% end %>
</div>

<% if @quote %>
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
    <table class="w-full text-sm text-left text-gray-400">
      <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th class="py-3 px-6">Company</th>
          <th class="py-3 px-6 text-center">Symbol</th>
          <th class="py-3 px-6 text-center">Latest Price</th>
          <th class="py-3 px-6 text-center">Change</th>
          <th class="py-3 px-6 text-center">Buy</th>
        </tr>
      </thead>
      <tbody>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
          <td class="py-3 px-6 font-medium whitespace-nowrap text-white"><%= @quote.company_name %></td>
          <td class="py-3 px-6 text-center"><%= @quote.symbol %></td>
          <td class="py-3 px-6 text-center"><%= number_to_currency(@quote.latest_price, precision: 2) %></td>
          <% if @quote.change < 0 %>
            <td class="py-3 px-6 text-red-600 text-center"><%= number_to_currency(@quote.change, precision: 2) %></td>
          <% else %>
            <td class="py-3 px-6 text-green-600 text-center"><%= number_to_currency(@quote.change, precision: 2) %></td>
          <% end %>
          <% if @stocks.where(symbol: @quote.symbol).any? && current_user.is_active %>
            <% @stock = @stocks.where(symbol: @quote.symbol)%>
            <td class="py-3 px-6 text-center"><%= link_to "Buy Shares", buy_stock_path({:stock_id => @stock.ids, :name => @quote.company_name, :symbol => @quote.symbol, :price => @quote.latest_price}), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline' %></td>
          <% elsif @stocks.where(symbol: @quote.symbol).any? && !current_user.is_active %>
            <td class="py-3 px-6 text-center">Prohibited</td>
          <% else %>
            <td class="py-3 px-6 text-center">Not Available</td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
<%# 
  <div class="w-full flex justify-center place-items-center mb-5">
    <p class="italic text-red-600">Symbol not found</p>
  </div> %>
<% end %>

<div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
  <h1 class="w-full text-center text-xl font-bold text-white mb-2">What We Offer</h1>
  <table class="w-full text-sm text-left text-gray-400">
    <thead class="text-xs uppercase bg-gray-700 text-gray-400">
      <tr>
        <th class="py-3 px-6">Company</th>
        <th class="py-3 px-6 text-center">Symbol</th>
        <th class="py-3 px-6 text-center">Latest Price</th>
        <th class="py-3 px-6 text-center">Change</th>
        <th class="py-3 px-6 text-center">Buy</th>
      </tr>
    </thead>
    <tbody>
      <% @stocks.each do |stock| %>
        <% @api = @client.quote(stock.symbol) %>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
          <td class="py-3 px-6 font-medium whitespace-nowrap text-white"><%= stock.name %></td>
          <td class="py-3 px-6 text-center"><%= stock.symbol %></td>
          <td class="py-3 px-6 text-center"><%= number_to_currency(@api.latest_price, precision: 2) %></td>
          <% if @api.change < 0 %>
            <td class="py-3 px-6 text-red-600 text-center"><%= number_to_currency(@api.change, precision: 2) %></td>
          <% else %>
            <td class="py-3 px-6 text-green-600 text-center"><%= number_to_currency(@api.change, precision: 2) %></td>
          <% end %>
          <% if current_user.is_active %>
            <td class="py-3 px-6 text-center"><%= link_to "Buy Shares", buy_stock_path({:stock_id => stock, :name => stock.name, :symbol => stock.symbol, :price => @api.latest_price}), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline' %></td>
          <% else %>
            <td class="py-3 px-6 text-center">Prohibited</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
  <h1 class="w-full text-center text-xl font-bold text-white mb-2">Trending Stocks</h1>
  <table class="w-full text-sm text-left text-gray-400">
    <thead class="text-xs uppercase bg-gray-700 text-gray-400">
      <tr>
        <th class="py-3 px-6">Company</th>
        <th class="py-3 px-6 text-center">Symbol</th>
        <th class="py-3 px-6 text-center">Latest Price</th>
        <th class="py-3 px-6 text-center">Change</th>
      </tr>
    </thead>
    <tbody>
      <% @client_list.each do |stock| %>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
          <td class="py-3 px-6 font-medium whitespace-nowrap text-white"><%= stock.company_name %></td>
          <td class="py-3 px-6 text-center"><%= stock.symbol %></td>
          <td class="py-3 px-6 text-center"><%= number_to_currency(stock.latest_price, precision: 2) %></td>
          <% if stock.change < 0 %>
            <td class="py-3 px-6 text-red-600 text-center"><%= number_to_currency(stock.change, precision: 2) %></td>
          <% else %>
            <td class="py-3 px-6 text-green-600 text-center"><%= number_to_currency(stock.change, precision: 2) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/traders/portfolio.html.erb
<h1 class="w-full text-center text-xl font-bold text-white mb-2">Portfolio</h1>
<div class="overflow-x-auto relative shadow-md sm:rounded-lg">
  <% if @unique.any? %>
    <table class="w-full text-sm text-left text-gray-400">
      <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th class="py-3 px-6">Company</th>
          <th class="py-3 px-6 text-center">Symbol</th>
          <th class="py-3 px-6 text-center">Total Shares</th>
          <th class="py-3 px-6 text-center">Current Price</th>
          <th class="py-3 px-6 text-center">Current Value</th>
          <th class="py-3 px-6 text-center"><span class="sr-only">View</span></th>
        </tr>
      </thead>
      <tbody>
        <% @unique.each do |transaction| %>
          <% @trans = @stocks.find(transaction.stock_id) %>
          <% @api =  @client.quote(@trans.symbol) %>
          <% @current_value = @api.latest_price * transaction.total_quantity %>
          <tr class="border-b bg-gray-800 border-gray-700  hover:bg-gray-600">
            <td class="py-3 px-6 font-mediumwhitespace-nowrap text-white"><%= @trans.name %></td>
            <td class="py-3 px-6 text-center"><%= @trans.symbol %></td>
            <td class="py-3 px-6 text-center"><%= transaction.total_quantity %></td>
            <td class="py-3 px-6 text-center"><%= number_to_currency(@api.latest_price, precision: 2) %></td>
            <td class="py-3 px-6 text-center"><%= number_to_currency(@current_value, precision: 2) %></td>
            <td class="py-3 px-6 text-center"><%= link_to 'View Details', stock_transactions_path(transaction.stock_id), class: 'font-medium text-blue-600 dark:text-blue-500 hover:underline' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>  
    <h2>You have no shares yet</h2>
  <% end %>
</div>

app/views/traders/transactions.html.erb
<h1 class="w-full text-center text-xl font-bold text-white mb-2">Transactions</h1>
<div class="overflow-x-auto relative shadow-md sm:rounded-lg">
  <% if @transactions.any? %>
    <table class="w-full text-sm text-left text-gray-400">
      <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th class="py-3 px-6">Company</th>
          <th class="py-3 px-6 text-center">Symbol</th>
          <th class="py-3 px-6 text-center">Type</th>
          <th class="py-3 px-6 text-center">Quantity</th>
          <th class="py-3 px-6 text-center">Amount</th>
          <th class="py-3 px-6 text-center">Date</th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |transaction| %>
          <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
            <td class="py-3 px-6 font-medium whitespace-nowrap text-white"><%= @stocks.find(transaction.stock_id).name %></td>
            <td class="py-3 px-6 text-center"><%= @stocks.find(transaction.stock_id).symbol %></td>
            <% if transaction.transaction_type == 'Buy' %>
              <td class="py-3 px-6 text-green-600 text-center"><%= transaction.transaction_type %></td>
            <% else %>
              <td class="py-3 px-6 text-red-600 text-center"><%= transaction.transaction_type %></td>
            <% end %>
            <td class="py-3 px-6 text-center"><%= transaction.quantity %></td>
            <td class="py-3 px-6 text-center"><%= number_to_currency(transaction.amount, precision: 2) %></td>
            <td class="py-3 px-6 text-center"><%= transaction.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>You have no transactions yet</p>
  <% end %>
</div>