config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  ##################################ADMINS ROUTES##################################
  get '/admin' => 'admins#dashboard', :as => 'admin_dashboard'
  get '/admin/transactions' => 'admins#transactions', :as => 'admin_transactions'
  post '/admin/users' => 'admins#create_user', :as => 'admin_create_user'
  get '/admin/users/new_user' => 'admins#new_user', :as => 'admin_new_user'
  get 'admin/users/:id/edit' => 'admins#edit_user', as: 'admin_edit_user'
  get 'admin/users/:id/activate' => 'admins#activate_user', as: 'admin_activate_user'
  get 'admin/users/:id/' => 'admins#show_user', as: 'admin_show_user'
  patch 'admin/users/:id' => 'admins#update_user', as: 'admin_update_user'
  #################################END ADMIN ROUTES#################################

  ##################################TRADERS ROUTES##################################
  get '/trader' => 'traders#dashboard', :as => 'trader_dashboard'
  get '/portfolio' => 'traders#portfolio', :as => 'trader_portfolio'
  get '/transactions' => 'traders#transactions', :as => 'trader_transactions'
  ################################END TRADERS ROUTES################################

  ################################TRANSACTIONS ROUTES###############################
  # get '/transactions' => 'transactions#index', :as => 'transactions'
  get '/stocks/:stock_id/transactions' => 'transactions#stock_transactions', :as => 'stock_transactions'
  post '/stocks/:stock_id/transactions' => 'transactions#create_stock_transaction', :as => 'create_stock_transactions'
  get '/stocks/:stock_id/transactions/buy' => 'transactions#buy', :as => 'buy_stock'
  get '/stocks/:stock_id/transactions/:id/sell' => 'transactions#sell', :as => 'sell_stock'
  patch '/stocks/:stock_id/transactions/:id' => 'transactions#update_transaction', :as => 'update_stock_transaction'
  ##############################END TRANSACTIONS ROUTES##############################

end

app/views/admins/activate_user.html.erb
<div class="w-full flex place-items-center justify-center">
  <div class="w-96">
    <%= form_with model: @user, url: admin_update_user_path, method: :patch,  local: true do |f| %>

      <div class="mb-2">
        <% if @user.errors.any? %>
          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
              <% end %>
          </ul>
        <% end %>
      </div>
      
      <h1 class ="mb-6 text-lg">Activate <span class="text-xl font-bold underline"><%= @user.email %></span>?</h1>
      <%= f.hidden_field :is_active, :value => true %>


      <div>
        <%= f.submit 'Activate User', class: 'w-full text-white focus:ring-4 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-blue-800 hover:cursor-pointer' %> 
      </div>
    <% end %>
  </div>
</div>

app/views/admins/dashboard.html.erb
<% if current_user %>
  <h1 class="w-full text-xl font-bold text-white mb-4">Welcome, <%= current_user.first_name.upcase %></h1>
  <div>
    <h1 class="w-full text-center text-xl font-bold text-white mb-2">Users with Pending Activation</h1>
      <div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-4">
        <% if @inactive_users.any? %>
          <table class="w-full text-sm text-left text-gray-400">
            <thead class="text-xs uppercase bg-gray-700 text-gray-400">
              <tr>
                <th class="py-3 px-6">Email</th>
                <th class="py-3 px-6 text-center">First Name</th>
                <th class="py-3 px-6 text-center">Last Name</th>
                <th class="py-3 px-6 text-center"><span class="sr-only">Edit</span></th>
                <th class="py-3 px-6 text-center"><span class="sr-only">Activate</span></th>
              </tr>
            </thead>
            <tbody>
              <% @inactive_users.each do |user| %>
                <tr class="border-b bg-gray-800 border-gray-700  hover:bg-gray-600">
                  <td class="py-3 px-6 font-medium whitespace-nowrap text-white"><%= user.email %></td>
                  <td class="py-4 px-6 text-center"><%= user.first_name %></td>
                  <td class="py-4 px-6 text-center"><%= user.last_name %></td>
                  <td class="py-4 px-6 text-center"><%= link_to "Edit User", admin_edit_user_path(user), class: 'font-medium text-blue-500 hover:underline' %></td>
                  <td class="py-4 px-6 text-center"><%= link_to "Activate User", admin_activate_user_path(user), class: 'font-medium text-blue-500 hover:underline' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p class="mb-4">No users with pending activation</p>
        <% end %>
      </div>
  </div>

  <div>
    <h1 class="w-full text-center text-xl font-bold text-white mb-2">Active Users</h1>
    <div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-4">
      <% if @active_users.any? %>
        <table class="w-full text-sm text-left text-gray-400">
          <thead class="text-xs uppercase bg-gray-700 text-gray-400">
            <tr>
              <th class="py-3 px-6">Email</th>
              <th class="py-3 px-6 text-center">First Name</th>
              <th class="py-3 px-6 text-center">Last Name</th>
              <th class="py-3 px-6 text-center"><span class="sr-only">Edit</span></th>
              <th class="py-3 px-6 text-center"><span class="sr-only">View</span></th>
            </tr>
          </thead>
          <tbody>
            <% @active_users.each do |user| %>
              <tr class="border-b bg-gray-800 border-gray-700  hover:bg-gray-600">
                <td class="py-3 px-6 font-mediumwhitespace-nowrap text-white"><%= user.email %></td>
                <td class="py-4 px-6 text-center"><%= user.first_name %></td>
                <td class="py-4 px-6 text-center"><%= user.last_name %></td>
                <td class="py-4 px-6 text-center"><%= link_to "Edit User", admin_edit_user_path(user), class: 'font-medium text-blue-500 hover:underline'  %></td>
                <td class="py-4 px-6 text-center"><%= link_to "View User", admin_show_user_path(user), class: 'font-medium text-blue-500 hover:underline' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No active users found</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admins/edit_user.html.erb
<div class="w-full flex place-items-center justify-center">
  <div class="w-96">
    <h1 class="w-full text-center mb-2">Edit User</h1>
    <h1 class="w-full text-center text-xl"><%= @user.email %></h1>

    <%= form_with model: @user, url: admin_update_user_path, method: :patch,  local: true do |f| %>


      <div class="mb-2">
        <% if @user.errors.any? %>
          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
              <% end %>
          </ul>
        <% end %>
      </div>
      
      <div class="mb-2">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-6">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.submit class: 'w-full text-white focus:ring-4 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-blue-800 hover:cursor-pointer' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/new_user.html.erb
<div class="w-full flex place-items-center justify-center">
  <div class="w-96">
    <h1 class="w-full text-center">New User</h1>

    <%= form_with model: User.new, url: admin_create_user_path,  local: true do |f| %>

      <%= f.hidden_field :role, :value => 'trader' %>

      <div class="mb-2">
        <% if @user.errors.any? %>
          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
              <% end %>
          </ul>
        <% end %>
      </div>
      
      <div class="mb-2">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-6">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.submit class: 'w-full text-white focus:ring-4 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-blue-800 hover:cursor-pointer' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/show_user.html.erb
<div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
  <h1 class="w-full text-center text-xl font-bold text-white mb-2">User Details</h1>
  <table class="w-full text-sm text-left  text-gray-400">
    <thead class="text-xs uppercase bg-gray-700 text-gray-400">
      <tr>
        <th class="py-3 px-6 text-center">Email</th>
        <th class="py-3 px-6 text-center">First Name</th>
        <th class="py-3 px-6 text-center">Last Name</th>
        <th class="py-3 px-6 text-center">Date Registered</th>
        <th class="py-3 px-6 text-center">Activated</th>
      </tr>
    </thead>
    <tbody>
        <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
          <td class="py-3 px-6 font-medium  whitespace-nowrap text-white"><%= @user.email %></td>
          <td class="py-3 px-6 text-center"><%= @user.first_name %></td>
          <td class="py-3 px-6 text-center"><%= @user.last_name %></td>
          <td class="py-3 px-6 text-center"><%= @user.created_at %></td>
          <% if @user.is_active %>
            <td class="py-3 px-6 text-center text-green-600">Yes</td>
          <% else %>
            <td class="py-3 px-6 text-center text-red-600">No</td>
          <% end %>
        </tr>
    </tbody>
  </table>
</div>

<div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
  <h1 class="w-full text-center text-xl font-bold text-white mb-2">Portfolio</h1>
  <% if @unique.any? %>
    <table class="w-full text-sm text-left  text-gray-400">
      <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th class="py-3 px-6 text-center">Company</th>
          <th class="py-3 px-6 text-center">Symbol</th>
          <th class="py-3 px-6 text-center">Quantity</th>
        </tr>
      </thead>
      <tbody>
        <% @unique.each do |uni| %>
        <% @stock = @stocks.find(uni.stock_id) %>
          <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
            <td class="py-3 px-6 font-medium  whitespace-nowrap text-white"><%= @stock.name %></td>
            <td class="py-3 px-6 text-center"><%= @stock.symbol %></td>
            <td class="py-3 px-6 text-center"><%= uni.total_quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>User has no company shares</p>
  <% end %>
</div>

<div class="overflow-x-auto relative shadow-md sm:rounded-lg mb-5">
  <h1 class="w-full text-center text-xl font-bold text-white mb-2">Transactions</h1>
  <% if @user.transactions.any? %>
    <table class="w-full text-sm text-left  text-gray-400">
      <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th class="py-3 px-6 text-center">Date</th>
          <th class="py-3 px-6 text-center">Type</th>
          <th class="py-3 px-6 text-center">Company</th>
          <th class="py-3 px-6 text-center">Symbol</th>
          <th class="py-3 px-6 text-center">Quantity</th>
          <th class="py-3 px-6 text-center">Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @user.transactions.each do |transaction| %>
        <% @stock = @stocks.find(transaction.stock_id) %>
          <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
            <td class="py-3 px-6 text-center"><%= transaction.created_at %></td>
            <% if transaction.transaction_type == 'Buy' %>
              <td class="py-3 px-6 text-green-600 text-center"><%= transaction.transaction_type %></td>
            <% else %>
              <td class="py-3 px-6 text-red-600 text-center"><%= transaction.transaction_type %></td>
            <% end %>
            <td class="py-3 px-6 text-center"><%= @stock.name %></td>
            <td class="py-3 px-6 text-center"><%= @stock.symbol %></td>
            <td class="py-3 px-6 text-center"><%= transaction.quantity %></td>
            <td class="py-3 px-6 text-center"><%= number_to_currency(transaction.amount, precision: 2) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>User has no transactions</p>
  <% end %>
</div>

app/views/admins/transactions.html.erb
<h1 class="w-full text-center text-xl font-bold text-white mb-2">Transactions</h1>
<div class="overflow-x-auto relative shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-400">
    <thead class="text-xs uppercase bg-gray-700 text-gray-400">
      <tr>
        <th class="py-3 px-6 text-center">Date</th>
        <th class="py-3 px-6 text-center">Type</th>
        <th class="py-3 px-6 text-center">User</th>
        <th class="py-3 px-6 text-center">Company</th>
        <th class="py-3 px-6 text-center">Symbol</th>
        <th class="py-3 px-6 text-center">Quantity</th>
        <th class="py-3 px-6 text-center">Price</th>
        <th class="py-3 px-6 text-center">Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr class=" border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
          <td class="py-3 px-6 text-center"><%= transaction.created_at %></td>
          <% if transaction.transaction_type == 'Buy' %>
            <td class="py-3 px-6 text-green-600 text-center"><%= transaction.transaction_type %></td>
          <% else %>
            <td class="py-3 px-6 text-red-600 text-center"><%= transaction.transaction_type %></td>
          <% end %>
          <td class="py-3 px-6 text-center"><%= @users.find(transaction.user_id).email %></td>
          <td class="py-3 px-6 text-center"><%= @stocks.find(transaction.stock_id).name %></td>
          <td class="py-3 px-6 text-center"><%= @stocks.find(transaction.stock_id).symbol %></td>
          <td class="py-3 px-6 text-center"><%= transaction.quantity %></td>
          <td class="py-3 px-6 text-center"><%= number_to_currency(transaction.price, precision: 2) %></td>
          <td class="py-3 px-6 text-center"><%= number_to_currency(transaction.amount, precision: 2) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>