config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  ##################################ADMINS ROUTES##################################
  get '/admin' => 'admins#dashboard', :as => 'admin_dashboard'
  get '/admin/transactions' => 'admins#transactions', :as => 'admin_transactions'
  post '/admin/users' => 'admins#create_user', :as => 'admin_create_user'
  get '/admin/users/new_user' => 'admins#new_user', :as => 'admin_new_user'
  get 'admin/users/:id/edit' => 'admins#edit_user', as: 'admin_edit_user'
  get 'admin/users/:id/activate' => 'admins#activate_user', as: 'admin_activate_user'
  get 'admin/users/:id/' => 'admins#show_user', as: 'admin_show_user'
  patch 'admin/users/:id' => 'admins#update_user', as: 'admin_update_user'
  #################################END ADMIN ROUTES#################################

  ##################################TRADERS ROUTES##################################
  get '/trader' => 'traders#dashboard', :as => 'trader_dashboard'
  get '/portfolio' => 'traders#portfolio', :as => 'trader_portfolio'
  get '/transactions' => 'traders#transactions', :as => 'trader_transactions'
  ################################END TRADERS ROUTES################################

  ################################TRANSACTIONS ROUTES###############################
  # get '/transactions' => 'transactions#index', :as => 'transactions'
  get '/stocks/:stock_id/transactions' => 'transactions#stock_transactions', :as => 'stock_transactions'
  post '/stocks/:stock_id/transactions' => 'transactions#create_stock_transaction', :as => 'create_stock_transactions'
  get '/stocks/:stock_id/transactions/buy' => 'transactions#buy', :as => 'buy_stock'
  get '/stocks/:stock_id/transactions/:id/sell' => 'transactions#sell', :as => 'sell_stock'
  patch '/stocks/:stock_id/transactions/:id' => 'transactions#update_transaction', :as => 'update_stock_transaction'
  ##############################END TRANSACTIONS ROUTES##############################

end

app/views/shared/_footer.html.erb
<footer class="w-full py-4 rounded-lg shadow bg-slate-900 relative flex-none">
    <hr class="my-2 border-gray-700">
    <span class="block text-sm sm:text-center text-gray-400">© 2022 JPLDG
    </span>
</footer>

app/views/shared/_navbar.html.erb
<nav class="py-2.5 bg-slate-900 flex-none">
  <div class="flex justify-between w-full">
    <div class="flex items-center">
      <%= link_to 'Avion Trading', root_path, class: "self-center text-2xl font-semibold whitespace-nowrap text-gray-300 hover:text-white" %>
    </div>
    <div>
      <ul class="flex pr-0 py-4 pl-4 gap-6 rounded-lg bg-slate-900">
        <% if current_user.present? %>
          <% if current_user.trader? %>
            <li>
              <%= link_to 'Home', trader_dashboard_path, class: "block py-2 px-4  rounded text-gray-400 hover:text-white" %>
            </li>
            <li>
              <%= link_to 'Portfolio', trader_portfolio_path, class: "block py-2 px-4  rounded text-gray-400 hover:text-white" %>
            </li>
            <li>
              <%= link_to 'Transactions', trader_transactions_path, class: "block py-2 px-4  rounded text-gray-400 hover:text-white" %>
            </li>
            <li>
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'font-medium text-blue-600 text-blue-500 hover:underline block py-2 px-4' %>
            </li>
          <% elsif current_user.admin? %>
            <li>
              <%= link_to 'Home', admin_dashboard_path, class: "block py-2 px-4  rounded text-gray-400 hover:text-white" %>
            </li>
            <li>
              <%= link_to 'Transactions', admin_transactions_path, class: "block py-2 px-4  rounded text-gray-400 hover:text-white" %>
            </li>
            <li>
              <%= link_to 'Add User', admin_new_user_path, class: 'block py-2 px-4  rounded text-gray-400 hover:text-white' %>
            </li>
            <li>
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'font-medium text-blue-500 hover:underline block py-2 px-4' %>
            </li>
          <% end %>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: 'font-medium text-blue-500 hover:underline' %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: 'font-medium text-blue-500 hover:underline' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>