config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  ##################################ADMINS ROUTES##################################
  get '/admin' => 'admins#dashboard', :as => 'admin_dashboard'
  get '/admin/transactions' => 'admins#transactions', :as => 'admin_transactions'
  post '/admin/users' => 'admins#create_user', :as => 'admin_create_user'
  get '/admin/users/new_user' => 'admins#new_user', :as => 'admin_new_user'
  get 'admin/users/:id/edit' => 'admins#edit_user', as: 'admin_edit_user'
  get 'admin/users/:id/activate' => 'admins#activate_user', as: 'admin_activate_user'
  get 'admin/users/:id/' => 'admins#show_user', as: 'admin_show_user'
  patch 'admin/users/:id' => 'admins#update_user', as: 'admin_update_user'
  #################################END ADMIN ROUTES#################################

  ##################################TRADERS ROUTES##################################
  get '/trader' => 'traders#dashboard', :as => 'trader_dashboard'
  get '/portfolio' => 'traders#portfolio', :as => 'trader_portfolio'
  get '/transactions' => 'traders#transactions', :as => 'trader_transactions'
  ################################END TRADERS ROUTES################################

  ################################TRANSACTIONS ROUTES###############################
  # get '/transactions' => 'transactions#index', :as => 'transactions'
  get '/stocks/:stock_id/transactions' => 'transactions#stock_transactions', :as => 'stock_transactions'
  post '/stocks/:stock_id/transactions' => 'transactions#create_stock_transaction', :as => 'create_stock_transactions'
  get '/stocks/:stock_id/transactions/buy' => 'transactions#buy', :as => 'buy_stock'
  get '/stocks/:stock_id/transactions/:id/sell' => 'transactions#sell', :as => 'sell_stock'
  patch '/stocks/:stock_id/transactions/:id' => 'transactions#update_transaction', :as => 'update_stock_transaction'
  ##############################END TRANSACTIONS ROUTES##############################

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :get_stock
  before_action :set_transaction, only: [:sell, :update_transaction]
  before_action :get_user
  before_action :check_authorization
  before_action :authenticate_user!

  def stock_transactions
    @transactions = @stock.transactions.where(user_id: @user.id, is_active: true)
    @stocks = Stock.all
    @client = IEX::Api::Client.new
  end

  def buy
    @transaction = @stock.transactions.build
  end

  def sell
  end

  def create_stock_transaction
    @transaction = @stock.transactions.build(transaction_params)
    @transaction.user_id = current_user.id
    
    if @transaction.save!
      redirect_to trader_transactions_path, notice: "Buy Transaction Successful"
    else
      render :buy
    end
  end

  def update_transaction
    old_price = @transaction.price
    old_amount = @transaction.amount
    if @transaction.update(is_active_params)
      @transaction.add_sell_transaction(old_price, old_amount)
      redirect_to trader_transactions_path, notice: "Sell Transaction Successful"
    else
      render :sell
    end
  end

  def destroy 
  end

  def get_stock
    @stock = Stock.find(params[:stock_id])
  end

  def set_transaction
    @transaction = @stock.transactions.find(params[:id])
  end

  def get_user
    @user = current_user
  end

  def check_authorization
    if current_user.role == 'admin'
      redirect_to admin_dashboard_path, notice: 'Access Denied'
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:stock_id, :user_id, :price, :quantity, :amount, :transaction_type, :is_active)
  end

  def is_active_params
    params.require(:transaction).permit(:is_active, :price, :amount)
  end
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/buy.html.erb
<div class="w-full flex place-items-center justify-center">
  <div class="w-96">
    <h1 class="w-full text-center">Buy Shares</h1>
    <%= form_with model: [@stock, @transaction], url: create_stock_transactions_path, local: true do |f| %>
      <%= f.hidden_field :transaction_type, :value => 'Buy' %>
      <%= f.hidden_field :is_active, :value => true %>
      <div>
        <% if @transaction.errors.any?  %>
          <ul>
            <% @transaction.errors..each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <div class="mb-2">
        <%= f.label :name %><br />
        <%= f.text_field :name, :value => params[:name], readonly: true,  class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.label :symbol %><br />
        <%= f.text_field :symbol, :value => params[:symbol], readonly: true,  class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.label :price %><br />
        <%= f.text_field :price, :value => params[:price], readonly: true, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div class="mb-2">

      <div class="mb-6">
        <%= f.label :quantity %><br />
        <%= f.number_field :quantity, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.submit 'Buy', class: 'w-full text-white focus:ring-4 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-blue-800 hover:cursor-pointer' %>
      </div>
        
    <% end %>
  </div>
</div>

app/views/transactions/sell.html.erb
<div class="w-full flex place-items-center justify-center">
  <div class="w-96">
    <h1 class="w-full text-center">Sell Shares</h1>
    <%= form_with model: [@stock, @transaction], url: update_stock_transaction_path, method: :patch, local: true do |f| %>

      <%= f.hidden_field :price, :value => params[:price] %>
      <%= f.hidden_field :is_active, :value => false %>
      <div>
        <% if @transaction.errors.any?  %>
          <ul>
            <% @transaction.errors..each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>

      <div class="mb-2">
        <%= f.label :name %><br />
        <%= f.text_field :name, :value => params[:name], readonly: true, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-2">
        <%= f.label :symbol %><br />
        <%= f.text_field :symbol, :value => params[:symbol], readonly: true, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>


      <div class="mb-2">
        <%= f.label :quantity %><br />
        <%= f.text_field :quantity, :value => params[:quantity], readonly: true, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

      <div class="mb-6">
        <%= f.label :amount %><br />
        <%= f.text_field :amount, :value => params[:amount], readonly: true, class: 'w-full border text-white text-sm rounded-lg focus:ring-blue-500 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500' %>
      </div>

    
      <div class="mb-2">
        <%= f.submit 'Sell', class: 'w-full text-white focus:ring-4 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-blue-800 hover:cursor-pointer' %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/transactions/stock_transactions.html.erb
<h1 class="mb-2">Your Positions for: <span class="text-xl font-bold"><%= @stock.name %>, <%= @stock.symbol %></span></h1>
<div class="overflow-x-auto relative shadow-md sm:rounded-lg">
  <% if @transactions.any? %>
    <table class="w-full text-sm text-left text-gray-400">
      <thead class="text-xs uppercase bg-gray-700 text-gray-400">
        <tr>
          <th class="py-3 px-6 text-center">Transaction Date</th>
          <th class="py-3 px-6 text-center">Quantity</th>
          <th class="py-3 px-6 text-center">Amount Spent</th>
          <th class="py-3 px-6 text-center">Current Value</th>
          <th class="py-3 px-6 text-center"><span class="sr-only">Sell</span></th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |transaction| %>
          <% @api = @client.quote(@stock.symbol) %>
          <% @current_value = @api.latest_price * transaction.quantity %>
          <tr class="border-b bg-gray-800 border-gray-700 hover:bg-gray-600">
            <td class="py-3 px-6 text-center"><%= transaction.created_at %></td>
            <td class="py-3 px-6 text-center"><%= transaction.quantity %></td>
            <td class="py-3 px-6 text-center"><%= number_to_currency(transaction.amount, precision: 2) %></td>
            <% if transaction.amount <= @current_value %>
              <td class="py-3 px-6 text-center text-green-600"><%= number_to_currency(@current_value, precision: 2) %></td>
            <% else %>
              <td class="py-3 px-6 text-center text-red-600"><%= number_to_currency(@current_value, precision: 2) %></td>
            <% end %>
            <td class="py-3 px-6 text-center"><%= link_to "Sell", sell_stock_path({:stock_id => @stock, :id => transaction.id, :name => @stock.name, :symbol => @stock.symbol, :price => @api.latest_price, :amount => @api.latest_price * transaction.quantity, :quantity => transaction.quantity}), class: 'font-medium text-blue-500 hover:underline' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>You have no positions on any company</p>
  <% end %>
</div>